name: Build and Deploy SC-Manager app to Firebase Hosting

on:
  push:
    branches:
      - "**"
  pull_request_target:
    branches:
      - "**"

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: .NET SDK einrichten
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Abhängigkeiten wiederherstellen
        run: dotnet restore

      - name: Setze Variablen
        uses: microsoft/variable-substitution@v1
        with:
          files: 'sc-manager/wwwroot/appsettings.Production.json'
        env:
          Firebase.ApiKey: ${{ secrets.FIREBASE_API_KEY }}
          Firebase.AuthDomain: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          Firebase.ProjectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          Firebase.StorageBucket: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          Firebase.MessagingSenderId: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          Firebase.AppId: ${{ secrets.FIREBASE_APP_ID }}

      - name: Blazor App veröffentlichen (Release-Build)
        run: dotnet publish ./sc-manager/sc-manager.csproj -c Release -o release

      - name: Firebase Hosting Verzeichnis vorbereiten
        run: |
          mkdir -p firebase-deploy
          cp -r release/wwwroot/* firebase-deploy/

      - name: Auf Firebase Hosting deployen
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
